#requires -Version 5.1
<#
.SYNOPSIS
  Install opencode-inline-chart into ~/.config/opencode for this machine.
#>
[CmdletBinding()]
param(
    [switch]$SkipTui
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$config = Join-Path $env:USERPROFILE ".config\opencode"
$pluginsDir = Join-Path $config "plugins"
$toolsDir = Join-Path $config "tools"

New-Item -ItemType Directory -Force -Path $pluginsDir, $toolsDir | Out-Null

# file:// with drive letter needs file:///C:/...
if ($root -match '^[A-Za-z]:') {
  $fileUrl = "file:///" + ($root -replace '\\', '/')
} else {
  $fileUrl = "file://" + ($root -replace '\\', '/')
}

# Prefer a single registration path: opencode.jsonc plugin[] → server module.
# Also install tools/create_inline_chart.ts so the tool is available even if
# the plugin loader only discovers tools/ (filename = tool name).
$toolDest = Join-Path $toolsDir "create_inline_chart.ts"
$toolLoader = @"
// Auto-generated by install.ps1 — thin tool wrapper
import { tool } from "@opencode-ai/plugin"
import { buildChart, formatToolOutput } from "$fileUrl/src/chart/build.ts"
import type { ChartRequest, ChartType } from "$fileUrl/src/chart/types.ts"

const chartTypes = ["line","bar","scatter","pie","area","heatmap","candlestick","boxplot"] as const

export default tool({
  description: "Render an interactive chart (ASCII + type:chart envelope). Prefer over code dumps for plots.",
  args: {
    chart_type: tool.schema.enum(chartTypes),
    title: tool.schema.string().optional(),
    data: tool.schema.array(tool.schema.record(tool.schema.string(), tool.schema.any())),
    x_field: tool.schema.string().optional(),
    y_field: tool.schema.string().optional(),
    series_field: tool.schema.string().optional(),
    options: tool.schema.object({
      show_trendline: tool.schema.boolean().optional(),
      show_legend: tool.schema.boolean().optional(),
      interactive: tool.schema.boolean().optional(),
      theme: tool.schema.enum(["dark","light"]).optional(),
      annotations: tool.schema.array(tool.schema.any()).optional(),
      height: tool.schema.number().optional(),
      moving_average: tool.schema.number().optional(),
      renderer: tool.schema.enum(["echarts","vega-lite"]).optional(),
    }).optional(),
  },
  async execute(args, context) {
    const req: ChartRequest = {
      chart_type: args.chart_type as ChartType,
      title: args.title,
      data: (args.data ?? []) as Array<Record<string, unknown>>,
      x_field: args.x_field,
      y_field: args.y_field,
      series_field: args.series_field,
      options: args.options as ChartRequest["options"],
    }
    const envelope = buildChart(req)
    context.metadata({
      title: envelope.meta.title || "Chart",
      metadata: { oc_plugins_chart: true, envelope },
    })
    return formatToolOutput(envelope)
  },
})
"@
Set-Content -Path $toolDest -Value $toolLoader -Encoding UTF8
Write-Host "Tool -> $toolDest"

# Remove stale dual loaders from plugins/ if present
Remove-Item (Join-Path $pluginsDir "inline-chart.ts") -Force -ErrorAction SilentlyContinue

# Wire opencode.jsonc plugin entry (file URL to server module)
$cfgPath = Join-Path $config "opencode.jsonc"
$pluginSpec = $fileUrl + "/src/server/index.ts"
if (Test-Path $cfgPath) {
  $raw = Get-Content $cfgPath -Raw
} else {
  $raw = '{ "$schema": "https://opencode.ai/config.json" }'
}

# Minimal merge: ensure plugin array contains our file URL
try {
  # Strip comments for parse attempt
  $jsonText = $raw -replace '(?m)^\s*//.*$', '' -replace '/\*[\s\S]*?\*/', ''
  $obj = $jsonText | ConvertFrom-Json
} catch {
  $obj = [pscustomobject]@{ '$schema' = 'https://opencode.ai/config.json' }
}

$plugins = @()
if ($obj.plugin) { $plugins = @($obj.plugin) }
if ($plugins -notcontains $pluginSpec -and -not ($plugins | Where-Object { "$_" -match 'inline-chart|opencode-inline-chart' })) {
  $plugins += $pluginSpec
}
$obj | Add-Member -NotePropertyName plugin -NotePropertyValue $plugins -Force

# Write pretty jsonc
$out = @{
  '$schema' = 'https://opencode.ai/config.json'
  plugin = $plugins
}
if ($obj.username) { $out.username = $obj.username }
($out | ConvertTo-Json -Depth 8) | Set-Content $cfgPath -Encoding UTF8
Write-Host "Updated $cfgPath plugin[] += $pluginSpec"

# 4) TUI config
if (-not $SkipTui) {
  $tuiPath = Join-Path $config "tui.json"
  $tuiPlugin = $fileUrl + "/src/tui/index.tsx"
  $tui = @{
    '$schema' = 'https://opencode.ai/tui.json'
    plugin = @($tuiPlugin)
  }
  if (Test-Path $tuiPath) {
    try {
      $existing = Get-Content $tuiPath -Raw | ConvertFrom-Json
      $tp = @()
      if ($existing.plugin) { $tp = @($existing.plugin) }
      if ($tp -notcontains $tuiPlugin) { $tp += $tuiPlugin }
      # preserve other keys
      $hash = @{}
      $existing.PSObject.Properties | ForEach-Object { $hash[$_.Name] = $_.Value }
      $hash['$schema'] = 'https://opencode.ai/tui.json'
      $hash['plugin'] = $tp
      $tui = $hash
    } catch { }
  }
  ($tui | ConvertTo-Json -Depth 8) | Set-Content $tuiPath -Encoding UTF8
  Write-Host "Updated $tuiPath"
}

# 5) Ensure package.json has plugin dep (already does)
Write-Host ""
Write-Host "Install complete."
Write-Host "  Restart OpenCode (opencode), then ask: Plot a line chart of ..."
Write-Host "  TUI: /chart after a chart is generated"
Write-Host "  Verify: opencode debug config"
